import { TableSchema } from "../components/main/table/table-schema";

export const UserSchema: TableSchema = {
  columns: [
    {
      key: "select",
      label: "Select",
      type: "select",
      visible: true,
    },
    {
      key: "username",
      label: "Username",
      type: "text",
      sortable: true,
      filterable: true,
      visible: true,
      editable: true,
    },
    {
      key: "email",
      label: "Email",
      type: "email",
      sortable: true,
      filterable: true,
      visible: true,
      editable: true,
    },
    {
      key: "provider",
      label: "Provider",
      type: "text",
      sortable: true,
      filterable: true,
      visible: true,
      editable: false,
    },
    {
      key: "confirmed",
      label: "Confirmed",
      type: "text",
      sortable: true,
      filterable: true,
      visible: true,
      editable: false,
    },
    {
      key: "blocked",
      label: "Status",
      type: "text",
      sortable: true,
      filterable: true,
      visible: true,
      editable: false,
    },
    {
      key: "createdAt",
      label: "Created At",
      type: "text",
      sortable: true,
      filterable: false,
      visible: true,
      editable: false,
    },
    {
      key: "updatedAt",
      label: "Updated At",
      type: "text",
      sortable: true,
      filterable: false,
      visible: true,
      editable: false,
    },
    {
      key: "publishedAt",
      label: "Published At",
      type: "text",
      sortable: true,
      filterable: false,
      visible: true,
      editable: false,
    },
    {
      key: "actions",
      label: "Actions",
      type: "actions",
      visible: true,
      editable: false,
    },
  ],
  title: "Users",
  description: "Manage your users and their details here.",
  searchKey: "username",
};
