import type { Metadata } from "next";
import localFont from "next/font/local";
import { Ubuntu_Mono, Courier_Prime } from "next/font/google"
import "./globals.css";

const ubuntu_mono = Ubuntu_Mono({
  weight: ["400", "700"],
  subsets: ["latin"]
})

const courier_prime = Courier_Prime({
  weight: ['400', '700'],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={ubuntu_mono.className}
      >
        {children}
      </body>
    </html>
  );
}
